return {
  {
    "nvim-treesitter/nvim-treesitter",
    branch = "master",
    lazy = false,
    build = ":TSUpdate",
    config = function()
      local configs = require("nvim-treesitter.configs")

      configs.setup({
        ensure_installed = {
          "bash",
          "c",
          "comment",
          "css",
          "dart",
          "dockerfile",
          "dot",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "go",
          "groovy",
          "html",
          "http",
          "java",
          "javadoc",
          "javascript",
          "jsdoc",
          "json",
          "jsonc",
          "kotlin",
          "lua",
          "luadoc",
          "luap",
          "markdown",
          "markdown_inline",
          "nginx",
          "php",
          "phpdoc",
          "python",
          "query",
          "regex",
          "sql",
          "ssh_config",
          "tsx",
          "typescript",
          "vim",
          "vimdoc",
          "xml",
          "yaml",
        },
        highlight = { enable = true },
        indent = { enable = true },
      })
    end,
  },
}
